// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE495DhOR3OsvrDlzayusuK__R0lkllNU',
    appId: '1:594343981380:web:cf26668e042117a555a711',
    messagingSenderId: '594343981380',
    projectId: 'job-finder-app-21ac8',
    authDomain: 'job-finder-app-21ac8.firebaseapp.com',
    storageBucket: 'job-finder-app-21ac8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3mRYaE0V0TEjy8CO7j0x5nfLVdqeNfco',
    appId: '1:594343981380:android:6ff0aaf1529f0f6f55a711',
    messagingSenderId: '594343981380',
    projectId: 'job-finder-app-21ac8',
    storageBucket: 'job-finder-app-21ac8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmkuRQpTIkMBPNt9wY86L4Fm0p3HytoXM',
    appId: '1:594343981380:ios:18fd6b4abccfc3b955a711',
    messagingSenderId: '594343981380',
    projectId: 'job-finder-app-21ac8',
    storageBucket: 'job-finder-app-21ac8.firebasestorage.app',
    iosBundleId: 'com.example.jobFinderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmkuRQpTIkMBPNt9wY86L4Fm0p3HytoXM',
    appId: '1:594343981380:ios:18fd6b4abccfc3b955a711',
    messagingSenderId: '594343981380',
    projectId: 'job-finder-app-21ac8',
    storageBucket: 'job-finder-app-21ac8.firebasestorage.app',
    iosBundleId: 'com.example.jobFinderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE495DhOR3OsvrDlzayusuK__R0lkllNU',
    appId: '1:594343981380:web:962a7de8085b83d255a711',
    messagingSenderId: '594343981380',
    projectId: 'job-finder-app-21ac8',
    authDomain: 'job-finder-app-21ac8.firebaseapp.com',
    storageBucket: 'job-finder-app-21ac8.firebasestorage.app',
  );
}
